language: node_js
node_js:
    - "node"
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"
    - cd ..
    - git clone https://github.com/peer2print/contracts.git
    - cd contracts
    - npm install
    - npm run start-testrpc
    - npm run migrate
    - cd ../core
script:  npm run test
